# Generated by Django 2.0.5 on 2018-05-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='mapfile',
            field=models.FileField(blank=True, null=True, upload_to='maps/'),
        ),
    ]
